= Antora - Doc as Code!!
:description: Como utilizar o Antora para agilizar o compartilhamento de conhecimento. 


== Para que serve o antora

O Antora é uma ferramenta especializada no compartilhamento ágil de conhecimento. Usando repositórios de código como por exemplo o github / gitlab como fonte de armazenamento, utiliza a metodologia conhecida como "doc as code". 

Este estilo de documentação visa organizar e democratizar a geração de conhecimento em times distribuídos. Isso é possível usando uma UI interativa, organizada e gerada de forma automatizada que usa como fonte de dados repositórios armazenado em ferramentas de controle de versão de código fonte, principalmente o Git.

Isso garante todo o poder de compartilhamento e colaboração de ferramentas como GIT e a facilidade de busca e organização provido por ferramentas voltadas para a gestão de conhecimento.

== Comece agora a criar o seu conteúdo

Para gerar conteúdo para sua equipe, basta inicializar um repositório no Git e seguir alguns poucos padrões.

Esses padrões ajudarão a ferramenta a gerar automaticamente a documentação do seu conteúdo de forma organizada e agradável.